AspNetCoreRoutingDemo/Controllers/AttributeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreRoutingDemo.Controllers
{
    [Route("users")]
    [Route("[controller]")]
    public class AttributeController : Controller
    {
        [HttpGet("")]
        [HttpGet("index")] //We generally want to use the more specific Http[Verb] attributes over the generic Route attribute
        
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("{id:int}")]
        public IActionResult ByID(int id)
        {
            ViewData["userID"] = id;
            return View();
        }

        [HttpGet("{dateOfBirth:datetime}")]
        public IActionResult ByDateOfBirth(DateTime dateOfBirth)
        {
            ViewData["dateOfBirth"] = dateOfBirth;
            return View();
        }

        [HttpPost("search/byDateOfBirth")]
        public IActionResult SearchByDateOfBirth(DateTime dateOfBirth)
        {
            return RedirectToAction("ByDateOfBirth", new { dateOfBirth = dateOfBirth.ToString("yyyy-MM-dd") });
        }

        [HttpPost("search/byID")]
        public IActionResult SearchByID(int id)
        {
            return RedirectToAction("ByID", new { id = id });
        }
    }
}

AspNetCoreRoutingDemo/Controllers/ConventionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreRoutingDemo.Controllers
{
    public class ConventionController : Controller
    {
        public IActionResult AllBlogs() //An example of using a single convention route for multiple actions.
        {
            return View("AllBlogs");
        }

        public IActionResult Index(int blogID)
        {
            ViewData["blogID"] = blogID;
            return View();
        }

        public IActionResult BlogPost(int blogID, int postID)
        {
            ViewData["blogID"] = blogID;
            ViewData["postID"] = postID;
            return View();
        }
    }
}

AspNetCoreRoutingDemo/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreRoutingDemo.Controllers
{
    public class DefaultController : Controller
    {
        public IActionResult Test()
        {
            return View();
        }

        public IActionResult Sample(int id)
        {
            ViewData["id"] = id;
            return View();
        }
    }
}

AspNetCoreRoutingDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreRoutingDemo.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

AspNetCoreRoutingDemo/Views/Attribute/ByDateOfBirth.cshtml
@{
    ViewData["Title"] = "ByDateOfBirth";
}

<h2>Date of Birth: @ViewData["dateOfBirth"]</h2>

<p>On this page, we would list all users with the specified date of birth.</p>

AspNetCoreRoutingDemo/Views/Attribute/ByID.cshtml
@{
    ViewData["Title"] = "ByID";
}

<h2>User #@ViewData["userID"]</h2>

<p>User details for User #@ViewData["userID"] .</p>

AspNetCoreRoutingDemo/Views/Attribute/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>On this page, we can search for users by ID or date of birth.</p>

<form asp-action="searchbydateofbirth" asp-controller="attribute" method="post">
    <h3>Search by Date of Birth</h3>
    <label>
        Date of Birth:
        <input type="date" id="dateOfBirth" name="dateOfBirth" value="@DateTime.Today.ToString("yyyy-MM-dd")" />
    </label>
    <br />
    <input type="submit" value="Search" />
</form>

<form asp-action="searchbyid" asp-controller="attribute" method="post">
    <h3>Search by ID</h3>
    <label>
        ID:
        <input type="text" id="id" name="id" />
    </label>
    <br />
    <input type="submit" value="Search" />
</form>

AspNetCoreRoutingDemo/Views/Convention/AllBlogs.cshtml
@{
    ViewData["Title"] = "AllBlogs";
}

<h2>All Blogs</h2>

<p>Here's all the blogs this site hosts.</p>

@{
    var random = new Random();
}

<ul>
    @for(int i = 0; i < 10; i++)
    {
        var nextBlog = random.Next(50);
        <li>
            @Html.ActionLink("Blog #" + nextBlog.ToString(), "index", new { blogID = nextBlog })
        </li>
    }
</ul>

AspNetCoreRoutingDemo/Views/Convention/BlogPost.cshtml
@{
    ViewData["Title"] = "BlogPost";
}

<h2>Blog Post #@ViewData["postID"]</h2>

<p>Finally, here's the page for the blog post.</p>

AspNetCoreRoutingDemo/Views/Convention/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Post List for Blog #@ViewData["blogID"]</h2>

<p>This is the index for Blog #@ViewData["blogID"].  On this page, you might see a list of all blog posts, or maybe just the most recent one.</p>

<p>We got to this page using one of the convention routes defined in the Startup.cs file.</p>

<p>We also use convention routes to get to the posts in this blog, such as the following:</p>

@{ 
    var random = new Random();
}

<ul>
    @for (int i = 0; i < 3; i++)
    {
        var postNumber = random.Next(200);
        <li>
            @Html.ActionLink("Blog Post #" + postNumber.ToString(), "blogpost", new { blogID = ViewData["blogID"], postID = postNumber })
        </li>
    }
</ul>

AspNetCoreRoutingDemo/Views/Default/Sample.cshtml
@{
    ViewData["Title"] = "Sample";
}

<h2>Sample (ID: @ViewData["id"])</h2>

@{
    var random = new Random();
    var nextPage = random.Next(20);
}

<p>
    Here's the Sample view.  
    Notice how just navigating to @Html.ActionLink("/default/sample/" + nextPage.ToString(), "sample", new { id = nextPage }) also works?
</p>
<p>
    Refresh the page to see more pages.
</p>

AspNetCoreRoutingDemo/Views/Default/Test.cshtml
@{
    ViewData["Title"] = "Test";
}

<h2>Test</h2>

<p>
    Here's the Test view.  The nice thing about Default routing is that if your app isn't 
    going to be terribly complicated, you probably don't need any custom routes.
</p>
<p>Check out the @Html.ActionLink("Sample page", "Sample", new {id = 4}) for more examples of the default route.</p>

AspNetCoreRoutingDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h2>ASP.NET Core Demystified - Routing Sample Project</h2>

<p>
    Routing is not all that complicated in ASP.NET Core, but it is powerful.  In this sample project,
    you will find samples of the default, convention-based, and attribute-based routing structures
    supported by ASP.NET Core
</p>

AspNetCoreRoutingDemo/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCoreRoutingDemo</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AspNetCoreRoutingDemo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Default" asp-action="Test">Default Routing</a></li>
                    <li><a asp-area="" asp-controller="Convention" asp-action="AllBlogs">Convention Routing</a></li>
                    <li><a asp-area="" asp-controller="Attribute" asp-action="Index">Attribute Routing</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>